version: '2'
services:
  db:
    image: postgres
  app:
    build: ./app
    volumes:
      - ./app:/opt/finances
    ports:
      - "5000:5000"
    command: >
      /bin/bash -c '
      cd src/Finances;
      dotnet watch run;'
    depends_on:
      - db
  web: 
    build: ./web
    volumes:
      - ./web:/opt/finances-web
    ports:
      - "8080:8080"
    command: npm run dev-server
    depends_on:
      - app